const data = [
  {
    id: 1,
    storeId: 81,
    type: "deal",
    title: "Hardees",
    expiry: "10-12-2023",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 2,
    storeId: 81,
    type: "coupon",
    expiry: "10-12-2023",
    title: "Hardees",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 3,
    storeId: 81,
    type: "coupon",
    title: "Hardees",
    expiry: "10-12-2023",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 4,
    storeId: 81,
    type: "coupon",
    title: "Hardees",
    image: "Hardees-logo.png",
    likes: 52,
    expiry: "10-12-2023",
  },
  {
    id: 5,
    storeId: 81,
    type: "coupon",
    title: "Hardees",
    image: "Hardees-logo.png",
    likes: 59,
    expiry: "10-12-2023",
  },
  {
    id: 6,
    storeId: 81,
    type: "coupon",
    expiry: "10-12-2023",
    title: "Hardees",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 7,
    storeId: 81,
    type: "coupon",
    expiry: "10-12-2023",
    title: "Hardees",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 8,
    storeId: 81,
    type: "coupon",
    expiry: "10-12-2023",
    title: "Hardees",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 9,
    storeId: 81,
    type: "coupon",
    expiry: "10-12-2023",
    title: "Hardees",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 10,
    storeId: 81,
    type: "coupon",
    expiry: "10-12-2023",
    title: "Hardees",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 11,
    storeId: 81,
    type: "coupon",
    expiry: "10-12-2023",
    title: "Hardees",
    image: "Hardees-logo.png",
    likes: 52,
  },
];

export default data;
