const data = [
  {
    id: 1,
    storeId: 81,
    type: "deal",
    url: "www.example.com",
    deal: "www.example.com/affiliateLink",
    title: "Get 60% OFF on all summer deals",
    expiry: new Date("2023-10-12").getTime(),
    image: "aliexpress.webp",
    details:
      "This can give you anything you want on 60% off, so avail the offer while it last",
    likes: 52,
  },
  {
    id: 2,
    storeId: 81,
    type: "coupon",
    code: "51FGVF",
    deal: "www.example.com/affiliateLink",
    expiry: new Date("2023-10-12").getTime(),
    title: "Get 60% OFF on all summer deals",
    details:
      "This can give you anything you want on 60% off, so avail the offer while it last it cann",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 3,
    storeId: 81,
    type: "coupon",
    code: "51FGVF",
    deal: "www.example.com/affiliateLink",
    title: "Get 60% OFF on all summer deals",
    expiry: new Date("2023-10-12").getTime(),
    details:
      "This can give you anything you want on 60% off, so avail the offer while it last",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 4,
    storeId: 81,
    type: "coupon",
    code: "51FGVF",
    deal: "www.example.com/affiliateLink",
    title: "Get 60% OFF on all summer deals",
    image: "Hardees-logo.png",
    details:
      "This can give you anything you want on 60% off, so avail the offer while it last",
    likes: 52,
    expiry: new Date("2023-10-12").getTime(),
  },
  {
    id: 5,
    storeId: 81,
    type: "coupon",
    code: "51FGVF",
    deal: "www.example.com/affiliateLink",
    title: "Get 60% OFF on all summer deals",
    image: "Hardees-logo.png",
    details:
      "This can give you anything you want on 60% off, so avail the offer while it last",
    likes: 59,
    expiry: new Date("2023-10-12").getTime(),
  },
  {
    id: 6,
    storeId: 81,
    type: "coupon",
    code: "51FGVF",
    deal: "www.example.com/affiliateLink",
    expiry: new Date("2023-10-12").getTime(),
    title: "HardeesGet 60% OFF on all summer deals",
    image: "Hardees-logo.png",
    details:
      "This can give you anything you want on 60% off, so avail the offer while it last",
    likes: 52,
  },
  {
    id: 7,
    storeId: 81,
    type: "coupon",
    code: "51FGVF",
    deal: "www.example.com/affiliateLink",
    expiry: new Date("2023-10-12").getTime(),
    title: "HardeesGet 60% OFF on all summer deals",
    details:
      "This can give you anything you want on 60% off, so avail the offer while it last",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 8,
    storeId: 81,
    type: "coupon",
    code: "51FGVF",
    deal: "www.example.com/affiliateLink",
    expiry: new Date("2023-10-12").getTime(),
    title: "HardeesGet 60% OFF on all summer deals",
    details:
      "This can give you anything you want on 60% off, so avail the offer while it last",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 9,
    storeId: 81,
    type: "coupon",
    code: "51FGVF",
    deal: "www.example.com/affiliateLink",
    expiry: new Date("2023-10-12").getTime(),
    title: "Get 60% OFF on all summer deals",
    details:
      "This can give you anything you want on 60% off, so avail the offer while it last",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 10,
    storeId: 81,
    type: "coupon",
    code: "51FGVF",
    deal: "www.example.com/affiliateLink",
    expiry: new Date("2023-10-21").getTime(),
    title: "HardeesGet 60% OFF on all summer deals",
    details:
      "This can give you anything you want on 60% off, so avail the offer while it last",
    image: "Hardees-logo.png",
    likes: 52,
  },
  {
    id: 11,
    storeId: 81,
    type: "coupon",
    code: "51FGVF",
    deal: "www.example.com/affiliateLink",
    expiry: new Date("2023-10-12").getTime(),
    title: "Get 60% OFF on all summer deals",
    details:
      "This can give you anything you want on 60% off, so avail the offer while it last",
    image: "Hardees-logo.png",
    likes: 52,
  },
];

export default data;
