const storeData = [
  {
    id: 0,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 1,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 2,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 3,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 4,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 5,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 6,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 7,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 8,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 9,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 10,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 11,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 12,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 13,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 14,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 15,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 16,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 17,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 18,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 19,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 20,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 21,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 22,
    name: "AliExpress",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 23,
    name: "12Ali",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 24,
    name: "AliExpress",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 25,
    name: "AliExpress",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 26,
    name: "AliExpress",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 27,
    name: "Mama",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 28,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 29,
    name: "Mama",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 30,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 31,
    name: "Mama",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 32,
    name: "Mama",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 33,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    id: 34,
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 35,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
    name: "Mama",
  },
  {
    id: 36,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 37,
    name: "Mama",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 38,
    name: "Mama",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 39,
    name: "Mama",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 40,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    id: 41,
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 42,
    name: "Mama",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 43,
    name: "Mama",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },

  {
    id: 45,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 46,
    name: "Mama",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 47,
    name: "Mama",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 48,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 49,
    name: "Mama",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },

  {
    id: 50,
    name: "Mcdonalds",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 51,
    name: "Mama",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 52,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mcdonalds",
    img: "aliexpress.webp",
  },
  {
    id: 53,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mcdonalds",
    img: "aliexpress.webp",
  },
  {
    id: 54,
    name: "Mcdonalds",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 55,
    name: "Mcdonalds",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    id: 56,
    name: "Mcdonalds",
    img: "aliexpress.webp",
  },

  {
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    id: 57,
    name: "KFC",
    img: "aliexpress.webp",
  },
  {
    id: 58,
    name: "Ikea",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 59,
    name: "Mama",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 60,
    name: "Mama",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 61,
    name: "Mama",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 62,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 63,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
    name: "Mama",
  },
  {
    id: 64,
    name: "Mama",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },

  {
    id: 65,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },

  {
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    id: 66,
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 67,
    name: "Mama",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 68,
    name: "Mama",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 69,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 70,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 71,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 72,
    name: "Mama",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 73,
    name: "Mama",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 74,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 75,
    name: "Mama",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 76,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },

  {
    id: 77,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mcdonalds",
    img: "aliexpress.webp",
  },
  {
    id: 78,
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    name: "Mama",
    img: "aliexpress.webp",
  },
  {
    id: 79,
    name: "Mcdonalds",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
  },
  {
    id: 80,
    name: "Mcdonalds",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 81,
    name: "Mcdonalds",
    img: "aliexpress.webp",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    keywords: ["Technology", "Processor", "PC", "PC"],
  },
  {
    id: 82,
    name: "Mcdonalds",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
  {
    id: 83,
    name: "Mcdonalds",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },

  {
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    id: 84,
    name: "KFC",
    img: "aliexpress.webp",
  },
  {
    id: 85,
    name: "Ikea",
    desc: "Testing testing 1 2 3. This is just a test sentence.",
    img: "aliexpress.webp",
  },
];

export default storeData;
